baseurl = ""
languageCode = "en-us"
title = "arkenthera.com"
[params.links]
  twitter = "http://twitter.com/arkenthera/"
  github = " https://github.com/arkenthera"
  youtube = "https://www.youtube.com/channel/UCPGrADP6f19Apbb068_23Nw"
  email = "arkenthera@gmail.com"
